### ISSUE TITLE
CreateFile SecurityContext parameter

### ISSUE THREAD

**Issue by dare2405** [TalAloni/SMBLibrary#170]
Hi, in createFile function, there is a securityContext parameter but as you can see in the below, that parameter is not assigned to anything.  What is that parameter for? My real question is how can i use smb 3.0 features in this library such as encryption or signing. English is not my native language so I don't understand very well. Can you explain to me little bit?

Thnx for reply.

![Ekran görüntüsü 2023-03-12 015524](https://user-images.githubusercontent.com/127447542/224515062-b8387ad7-9285-4793-98de-2042f51f00b3.png)

**Comment by TalAloni** [comment]
The securityContext parameter is used for impersonation purposes - to assign a remote user logging in via SMB a local identity against the local filesystem, i.e. when the library runs under user "A" but you want to perform file related operations using user "B" (there are various reasons why this may be desired).
Note that this is not something that is built-in - the developer needs to implement the necessary logic as appropriate for the application (calling ImpersonateLoggedOnUser etc.) - that's why the securityContext parameter seems unused - however its existence is crucial for such scenarios.

Encryption and signing are negotiated automatically as appropriate. if the server or client require them they will be used.

**Comment by dare2405** [comment]
thnx for your reply.
