### ISSUE TITLE
Create a server in Linux

### ISSUE THREAD

**Issue by mghcool** [TalAloni/SMBLibrary#173]
How to create an SMB server in Linux?

Can you use a code example?

**Comment by TalAloni** [comment]
Just like you create it in Windows but with INTFileStore shares that are not dependent on Windows, such as NTFileSystemAdapter

**Comment by ESEricWare** [comment]
Hi.

is there anywhere an example for that NTFileSystemAdapter?
If not, could you please share an example?

thanks a lot

**Comment by TalAloni** [comment]
https://github.com/TalAloni/SMBLibrary/blob/master/SMBLibrary.Adapters/NTFileSystemAdapter/NTFileSystemAdapter.cs

**Comment by ESEricWare** [comment]
> https://github.com/TalAloni/SMBLibrary/blob/master/SMBLibrary.Adapters/NTFileSystemAdapter/NTFileSystemAdapter.cs

Thank you I already found it.
The question is how to initialize it?
Which classes are implementing IFileSystem?

**Comment by TalAloni** [comment]
Unlike Windows, where a ready-made NTDirectoryFileSystem implementation is already provided, if you want to run a server in Linux, it is up to you to provide the file-system implementation.
NTFileSystemAdapter is not a file-system implementation but rather an adapter that may be helpful to beginners to implement with the simplified IFileSystem instead of the more complex NTDirectoryFileSystem.

There is a (very old) example of implementing IFileSystem here:
https://github.com/TalAloni/SMBLibrary/tree/9fe283762a21546be5787735a6fe719fa2e20172/SMBServer/DirectoryFileSystem
