### ISSUE TITLE
How to determine the AccessRight a user has on a file or directory?

### ISSUE THREAD

**Issue by MedFehmiEBF** [TalAloni/SMBLibrary#175]
Hi Tal, 
I would like to appreciate your efforts and thank you a lot for providing the library with the many features it supports.

I have a **question**: What is the correct way to determine the access rights (read only / write) a user has on a specific file or directory?

**Comment by TalAloni** [comment]
Hi,
There are two types of permissions:
SMB-server level permissions and file-system level permissions,
So for example, write access on share "X" can be blocked on the share level for some users, and for others, the operation may succeed or fail depending on the permissions assigned to the user performing the operation (impersonation may be used here, or not).
Instead of predetermining whether the operation can succeed, which can be quite complex depending on all these factors, the common practice is to just try and have the client application handle accordingly when there is an error due to lack of permissions.
