### ISSUE TITLE
Hello, can you please tell me how Windows deletes files?

### ISSUE THREAD

**Issue by nvd05** [TalAloni/SMBLibrary#209]
Hello, can you please tell me how Windows deletes files?

Windows does not use the `FileDispositionInformation` class for some reason.
But I don't understand how it deletes the file.
Can you please explain?

I need this for the cart, as I have to get a delete request and replace it with a move.

> The images can be enlarged. Click on it and you will be redirected to the picture

### List
![image](https://i.stack.imgur.com/g3Hzi.png)

### 1 (CreateFile)
![image](https://i.stack.imgur.com/2nVIP.png)
![image](https://i.stack.imgur.com/GRM0b.jpg)

### 2 (GetInfo - Wireshark, QueryInfoRequest - Rider)
![image](https://i.stack.imgur.com/7B1T0.png)
![image](https://i.stack.imgur.com/1ozfV.jpg)

### 3 (GetInfo - Wireshark, QueryInfoRequest - Rider)
![image](https://i.stack.imgur.com/KlLn3.png)
![image](https://i.stack.imgur.com/a2zI2.jpg)

### 4 (CloseFile)
![image](https://i.stack.imgur.com/klbn7.png)
![image](https://i.stack.imgur.com/P6FCB.jpg)

**Comment by TalAloni** [comment]
This issue section is dedicated to issues with the library.
Under SMB2 the standard way to delete files is by using FileDispositionInformation. (there are niche ways to delete files by using IOCTLs but that's not used in practice)
The packet session you submitted does not include any command related to file deletion, however your conclusion that "Windows does not use the FileDispositionInformation class for some reason" is incorrect.

I'm closing the issue since it does not point to any issue with the library.

**Comment by nvd05** [comment]
Thanks for the IOCTL, as Windows uses it to delete files.

Can you please tell me where I can ask questions about Windows and SMB? The thing is that I have been looking at SMB documentation (looking at it, not reading it, i.e. I know the logic very superficially) and you know the logic completely, so you can help and tell me where to look for a solution or problem. On forums there are very limited number of people who know SMB and what it is in general, so the chance to get help is much lower.

For questions about logic: SMB, Windows, and so on - could you create another repository to discuss all of this?

**Comment by TalAloni** [comment]
> For questions about logic: SMB, Windows and so on - could you create another repository to discuss issues unrelated to your library?

No, I do not want nor have the time for additional responsibilities.
