### ISSUE TITLE
Cannot get SACL_SECURITY_INFORMATION from GetSecurityInformation - getting STATUS_ACCESS_DENIED

### ISSUE THREAD

**Issue by nddipiazza** [TalAloni/SMBLibrary#21]
Hi,

This may not be a valid issue but I figured I'd send some info anyways.

I am attempting to get the security information from a file using the `SMBLibrary`.

My user is an admin and has full access to the file and the entire share.

I try to get the SACL:

```
status = tree.GetSecurityInformation(out SecurityDescriptor securityDescriptor,
                   handle,
                   SecurityInformation.SACL_SECURITY_INFORMATION)
```

When I try this, I get an error:

```
71	9.074730848	192.168.1.229	192.168.1.57	SMB2	174	GetInfo Request SEC_INFO/SMB2_SEC_INFO_00 File: nick - Copy (2).txt
72	9.082573875	192.168.1.57	192.168.1.229	SMB2	143	GetInfo Response, Error: STATUS_ACCESS_DENIED
```

Wireshark here: https://drive.google.com/file/d/15uC01XA_xMszqfcmHEFCOj--x83fG21d/view?usp=sharing

I can retrieve DACLs, Group ACL and User ACL just fine.

**Comment by TalAloni** [comment]
I was able to get Owner / Group / DACL but had a similar issue with SACL and never looked into it until now.
According to the docs in order to get SACL the access mask should include ACCESS_SYSTEM_SECURITY.
If you can capture a communication between a Microsoft SMB client requesting SACL and a Microsoft SMB server then the required parameters will become clear.
