### ISSUE TITLE
WindowsCE / .NET Compact support

### ISSUE THREAD

**Issue by EndlessDelirium** [TalAloni/SMBLibrary#25]
This library would be a potential candidate for integrating SMBv2 support in WindowsCE based products. Is this something you'd be interested in to officially support? I already started a quick port at
https://github.com/EndlessDelirium/SMBLibrary/tree/features/WindowsCE

**Comment by TalAloni** [comment]
Hi and thank you, I'm a big fan of supporting legacy systems when the effort is reasonable and I wrote the library with the goal that it would be usable on multiple platforms.
With that said, after taking a good look at the changes in your initial commit, some of the changes require a dependency that may complicate things for other developers who wish to work on this library. because of this reason and others, I would rather that the WindowsCE support will be maintained in a separate port.

As you astutely observed, the client does have some way to go (SMB 3.0 encryption support and etc.),
however, those features are currently not a priority for me so I'm not sure when they will materialize.
