### ISSUE TITLE
Support for SMB3

### ISSUE THREAD

**Issue by Cairn23** [TalAloni/SMBLibrary#26]
Are you intending to support SMB 3.x versions with the library. Reading the SMB specifications its hard to determine what would be required.

**Comment by TalAloni** [comment]
I will gladly accept a pull request.
I currently do not have any immediate plans to support SMB3, it shouldn't be too hard to implement the minimal features but I don't have much free time.

**Comment by TalAloni** [comment]
SMB 3.0 support was added in v1.4.3, client now supports encryption.

**Comment by HdfCRM** [comment]
Hello,

Is it possible to add an option or config context to force smb3 (for encrypt network packet !) 

because currently, my files transit without being encrypted even though I have SMB3 activated on my server
Thank you so much !

![image (4)](https://github.com/TalAloni/SMBLibrary/assets/109085599/64bc32e5-e5c2-4e29-8102-abfbe6da9a26)

**Comment by TalAloni** [comment]
@HdfCRM the question is unrelated to this closed issue.
The question is poorly phrased - the server cannot force the client to do anything, the server can reject clients and requests, forcing users to use various clients and settings.
