### ISSUE TITLE
Please make it possible to connect using SMBClients providing custom ports.

### ISSUE THREAD

**Issue by lezli01** [TalAloni/SMBLibrary#261]
In our use case we usually forward SMB server ports on non-default port values. For this we would like to utilize this package but currently we are not able as the port value is hardcoded based on which method is choosen for connection. Please make connection interfaces for SMBClients where the developer is able to provide custom port values regardless of what transport method is selected.

It might not be a heavy lift since the internal API's already utilize such functionality:
`protected internal bool Connect(IPAddress serverAddress, SMBTransportType transport, int port, bool forceExtendedSecurity, int responseTimeoutInMilliseconds)`

Some use-cases for which this would be beneficial:
* for security reasons it is not advisable to promote services on default ports for companies to avoid portmapping attacks
* on windows when I create an SMB server container I need to map it to other port as the default one is already occupied

Thank you in advance! <3

**Comment by TalAloni** [comment]
Hi,
Specifying ports is useful for a small group of developers but confuse majority of developers, that's why I try to "hide" it in a way that only those sophisticated developers that really need it will find it.

In v1.5.2 you could have used reflection to specify custom port.
In the upcoming v1.5.3 it will be even simpler and 'Connect' was changed to be 'protected internal', so you could use inheritance to expose it.

**Comment by lezli01** [comment]
Do you have an ETA for that perhaps? <3

**Comment by TalAloni** [comment]
v1.5.3 was just released.
