### ISSUE TITLE
Question: Will this library support SMBv3 anytime in near future

### ISSUE THREAD

**Issue by DipenInfoMedia** [TalAloni/SMBLibrary#51]
Hi,

I really appreciate the work you have done and this nuget package has been very helpful. Thanks for that

I was wondering if this package will be upgraded to support SMBv3 as well. We are seeing a situation where we will need to access shared folders that only allow SMBv3.

Or are you aware of any other alternative library that we can try for SMBv3 for now.

Thanks,
Dipen

**Comment by TalAloni** [comment]
Hi Dipen,
Can you provide a list of major products / services that supports SMB v3 but do not support SMB v2?
SMB v3 is an extension rather than a new protocol, the only desirable feature that SMB v3 adds is encryption IMO.
When a clear case will be presented to add encryption support - I'll consider it.

**Comment by DipenInfoMedia** [comment]
Hi Tal,

It is not that the product does not support SMB v2, but the plan is to enforce using only SMB v3 by the client and you are right it is mainly for encrytion.

Thanks,
Dipen
