### ISSUE TITLE
How to properly manage connections?

### ISSUE THREAD

**Issue by arielmoraes** [TalAloni/SMBLibrary#59]
As I couldn't find any documentation regarding connection guidelines I opened this as an issue.

We have 3 important components to access a file: `SMB2Client`, `ISMBFileStore` and the `FileID`. Suppose we have several access to the same share/file, what is the recomended approach to manage the connections? Should I have a pooling for the `SMB2Client` instances and call `TreeConnect` and `CreateFile` for each access? That is, what components should we share between file reads/writes?

**Comment by TalAloni** [comment]
There is no single correct answer as this depend on the application.
One obvious example of when you wish to use different connections is when you have a set of "tasks" to perform on behalf on different users, in that case you would want to avoid using an established connection for user A to perform operations on behalf of use B, and you would also want to close all files user A opened before performing operations on behalf of user B. (otherwise you may prevent the operation from succeeding).
In the above example, keeping a connection and shares for each user may save a few round-trips.
for each application you have to decide what optimizations can be made and whether they are worth the trouble or not.

**Comment by arielmoraes** [comment]
I forgot to describe my application. It is a simple API that provides an endpoint for the user to download the file. It is a Single share and only the API user (server) will access the files. 

So the question now is, if I need parallel operations, can the `SMB2Client` and `ISMBFileStore` handle it?

**Comment by TalAloni** [comment]
Currently no, the client was not designed to support parallelism.
if you need to perform multiple operations at the same time, you should use a separate client instance for each operation.

**Comment by arielmoraes** [comment]
Got it, thank you for your time.

**Comment by piotrpuszk** [comment]
> Currently no, the client was not designed to support parallelism. if you need to perform multiple operations at the same time, you should use a separate client instance for each operation.

Is this still true?

**Comment by TalAloni** [comment]
Yes, still true.

**Comment by TalAloni** [comment]
@mztung98 as long as you are performing all operations sequentially, you are file using a single SMB2Client.
