### ISSUE TITLE
DFS support?

### ISSUE THREAD

**Issue by nddipiazza** [TalAloni/SMBLibrary#63]
I notice some "Not implemented" exceptions around DFS for this SMB client code. 

Namely: https://github.com/TalAloni/SMBLibrary/blob/master/SMBLibrary/DFS/ResponseGetDfsReferral.cs

Am I correct in assuming this library does not yet support DFS?

**Comment by TalAloni** [comment]
Yes. it's not supported at the moment. (both client side & server side)
This is the first time anybody shows interest in  this BTW.

**Comment by nddipiazza** [comment]
Yeah the smbj library (basically the java version of this) has DFS support but it doesn't do caching. So I was going to see if I can compare with this library. The tricky part about DFS is you really need access to a system that has it implemented. It's really hard to get a test lab of it working.

**Comment by tokotech** [comment]
same issue here

**Comment by jahales** [comment]
@TalAloni would you be open to me porting portions of the smbj library (Apache 2.0 license) over to enable DFS? I would probably create an abstraction layer over ISMBClient / ISMBFileStore to handle DFS resolution & caching and keep the implementation separate from the core code.

**Comment by TalAloni** [comment]
Jacob, you can create your own fork and you don't need my permission for that.
(it's unlikely that I will pull Apache 2.0 licensed work though)

**Comment by MedFehmiEBF** [comment]
> @TalAloni would you be open to me porting portions of the smbj library (Apache 2.0 license) over to enable DFS? I would probably create an abstraction layer over ISMBClient / ISMBFileStore to handle DFS resolution & caching and keep the implementation separate from the core code.

Hi @jahales, if I may ask you! Did you make any progress regarding DFS support?

**Comment by jahales-intel** [comment]
@MedFehmiEBF I do have some functional DFS support in my internal repository. I could look into getting it into a shareable state and put it up in a fork.

**Comment by MedFehmiEBF** [comment]
> @MedFehmiEBF I do have some functional DFS support in my internal repository. I could look into getting it into a shareable state and put it up in a fork.

@jahales Thanks a lot for your efforts, I am looking forward to see your fork coming to live soon. Any idea already when do you plan to share it?

**Comment by jahales-intel** [comment]
> @jahales Thanks a lot for your efforts, I am looking forward to see your fork coming to live soon. Any idea already when do you plan to share it?

Instead of a fork, I created a separate repository that references SMBLibrary via Nuget package: https://github.com/jahales-intel/SMBLibrary.Contrib. I haven't had time to invest in documentation, unit testing and the like, so use at your own risk :). The DFS is only client-side. I've tested from Linux against an IT-supported NetApp (I don't have any visibility into how the server is setup). I recommend starting with SmbFileStream.

@TalAloni please let me know if you have any concerns with my strategy here and I will correct it. Thanks for all your great work on the base SMB library and I'm happy to share anything I have developed here for SMB with your project.

**Comment by TalAloni** [comment]
@jahales-intel Thanks, I don't see any problem with the manner in which you used the library.

**Comment by christapley-rt** [comment]
Hello @jahales, I'm assuming you're the same person as @jahales-intel. would you happen to still have the https://github.com/jahales-intel/SMBLibrary.Contrib repo? Thank you

**Comment by jahales** [comment]
> Hello [@jahales](https://github.com/jahales), I'm assuming you're the same person as @jahales-intel. would you happen to still have the https://github.com/jahales-intel/SMBLibrary.Contrib repo? Thank you

@christapley-rt Unfortunately I lost access when I left Intel.

**Comment by MedFehmiEBF** [comment]
Hey @jahales when you first released the library to GitHub I got the chance to fork it and download it locally to test it within our environment. I still have the project locally with an upgraded version to .net 9.0, so If you would like to, since you're the original author, I can send it to you, so you can make it again maintainable and available.
