### ISSUE TITLE
INTFileStore VirtualFS implementation

### ISSUE THREAD

**Issue by ciamberlini** [TalAloni/SMBLibrary#7]
Have you already tried to implement virtual share tree based on DB content?
It is sufficient to make a new class based on INTFileStore for this?

This lib is really cool, great work!

**Comment by TalAloni** [comment]
Hi, Thanks,
The library was designed to support all kinds of virtual file systems,
I haven't implemented one based on DB content, but it's definitely possible.
if you want fine control over the file system then implementing the low-level INTFileStore is the way to go.
Another possibility is to implement the more basic IFileSystem (and let the adapter class do the heavy lifting), I would probably start there because it's much easier to implement (at the cost of granularity).

**Comment by ciamberlini** [comment]
Thank you! I'll try with IFilesystem interface :-)

**Comment by TalAloni** [comment]
Yes, there is a long explanation, but the gist is that SMB library allows you a fine control over which user can access which directory / file at the share level, so I felt it wasn't really necessary in IFileSystem as well.
(the lower-level INTFileStore.CreateFile does have a securityContext parameter)

p.s. Here is an (old) example that implements IFileSystem:
https://github.com/TalAloni/SMBLibrary/tree/9fe283762a21546be5787735a6fe719fa2e20172/SMBServer/DirectoryFileSystem

**Comment by ciamberlini** [comment]
Thanks you!

**Comment by lenovo96166** [comment]
great job！
