### ISSUE TITLE
Connection Flow

### ISSUE THREAD

**Issue by rajatjhaexate** [TalAloni/SMBLibrary#91]
Hi, I really need help to understand the flow of an smb connection. when do I logoff and disconnect? Do I have to create a new object of SMB Client every time I need to connect to the smb file share or can I create a common SMB client global property and use that for all my uploads & downloads

**Comment by TalAloni** [comment]
1. A client instance needs to login once and after you're done with it you need to logout (once). once you logout the client is "dead" and you need to instantiate a new client.
2. after you login you need to connect to share, you can connect to multiple shares, and you can disconnect when you're done with them. all shares will be disconnected when you logout.
3. You certainly can use one client for all your uploads and downloads. however due to implementation limitations you cannot issue more than one pending command at a time so it would be more efficient not to limit yourself to one client.

**Comment by rajatjhaexate** [comment]
Thank you so much
